### ISSUE TITLE
UnicodeEncodeError in the cleanup

### ISSUE THREAD

**Issue by blackbunt** [blackbunt/dump-discogs-collection-2-csv#6]
Problem with release https://www.discogs.com/de/release/6867159

The release is included in the collection output file.

Error Messeage in the log:

--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\x\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 46-54: character maps to <undefined>
Call stack:
  File "C:/Users/x/PycharmProjects/DumpDisogs2Csv/DumpDiscogs.py", line 78, in <module>
    _db = collection.get_collection(username, apitoken)
  File "module\get_collection.py", line 122, in get_collection
    + clean.cleanup_title_url(row['album_title']) + ".png"
  File "module\cleanup_strings.py", line 71, in cleanup_title_url
    title = cleanup_title(input)
  File "module\cleanup_strings.py", line 59, in cleanup_title
    logger.debug(input + " -> " + title)
Message: 'براكتيكوم ين دآركاريبيك -> براكتيكوم ين دآركاريبيك'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\x\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 50-58: character maps to <undefined>
Call stack:
  File "C:/Users/x/PycharmProjects/DumpDisogs2Csv/DumpDiscogs.py", line 78, in <module>
    _db = collection.get_collection(username, apitoken)
  File "module\get_collection.py", line 122, in get_collection
    + clean.cleanup_title_url(row['album_title']) + ".png"
  File "module\cleanup_strings.py", line 74, in cleanup_title_url
    logger.debug(input + " -> " + title)
Message: 'براكتيكوم ين دآركاريبيك -> براكتيكوم-ين-دآركاريبيك'
Arguments: ()

**Comment by blackbunt** [comment]
fixed in the pre release version
